name: Build Claude Desktop MCP Manager

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Test application
      run: |
        python -c "import mcp_manager; print('Import successful')"

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "Claude-MCP-Manager-${{ matrix.os }}" mcp_manager.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable-${{ matrix.os }}-python${{ matrix.python-version }}
        path: |
          dist/Claude-MCP-Manager-*
          dist/Claude-MCP-Manager-*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: release-artifacts
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Claude Desktop MCP Manager ${{ github.ref }}
        body: |
          ## Claude Desktop MCP Manager Release
          
          ### Features
          - Visual MCP server management
          - Cross-platform support
          - Configuration safety with backups
          - Custom path configuration
          
          ### Downloads
          - Windows: `Claude-MCP-Manager-windows-latest.exe`
          - macOS: `Claude-MCP-Manager-macos-latest`
          - Linux: `Claude-MCP-Manager-ubuntu-latest`
          
          ### Installation
          1. Download the appropriate executable for your platform
          2. Run the executable directly (no installation required)
          3. Configure your Claude Desktop paths in Settings if needed
          
          ### Attribution
          Created by [Dawid](https://dawid.ai)
          
          Please maintain attribution when distributing or modifying.
        draft: false
        prerelease: false